### ISSUE TITLE
Mapa Mental

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/actividad-4-mapa-mental-calidad-de-software-yanet-02#1]
[Mapa Mental_Yanet González García..pdf](https://github.com/user-attachments/files/17107121/Mapa.Mental_Yanet.Gonzalez.Garcia.pdf)

**Comment by josealfredo79** [comment]
Calificacion..???

**Comment by Julissamigdalia** [comment]
Buen trabajo.
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
